[project]
name = "langchain-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docx2txt>=0.9",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "huggingface>=0.0.1",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-mistralai>=1.1.6",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.63.0",
    "tiktoken>=0.14.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
    "uvicorn>=0.52.4",
]
